// @keepTs
// @ts-nocheck
export declare class GlobalDefine {
    static readonly HTTPS = "https";
    static readonly USER_AGENT = "user_agent";
    static readonly TID = "tid";
    static readonly EXTERNAL_INFO = "external_info";
    static readonly HAS_ALIPAY = "has_alipay";
    static readonly HAS_MSP = "has_msp_app";
    static readonly UTDID = "utdid";
    static readonly APP_KEY = "app_key";
    static readonly KEY_RSA = "trideskey";
    static readonly NEW_CLIENT_KEY = "new_client_key";
    static readonly PA = "pa";
    static readonly EX_APP_ACTION = "android.app.intent.action.APP_EXCEPTION_OCCUR";
    static readonly EX_APP_BIZTYPE = "alipaySdk";
    static readonly EX_APP_EXNAME_BINDFAILD = "bindServiceFail";
    static readonly EX_APP_EXNAME_BINDTIMEOUT = "bindServiceTimeout";
    static readonly EX_APP_EXNAME_BINDEX = "bindServiceEx";
    static readonly EX_APP_EXNAME_StartActFail = "startActivityEx";
}
